// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQJzZ3kaAjRr_7LSbbDp88fapLph32AGE',
    appId: '1:226303495126:web:d3cbcd49aa3f77b37af277',
    messagingSenderId: '226303495126',
    projectId: 'bonding-bdf7a',
    authDomain: 'bonding-bdf7a.firebaseapp.com',
    storageBucket: 'bonding-bdf7a.firebasestorage.app',
    measurementId: 'G-M19WT5XT79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXJkJWq671ER6BhZDp0mrdPBugaI71o8',
    appId: '1:226303495126:android:0cbca5b8f635013a7af277',
    messagingSenderId: '226303495126',
    projectId: 'bonding-bdf7a',
    storageBucket: 'bonding-bdf7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOzmhcLX8GCPFmBExlWPXUR5qUrATYD4',
    appId: '1:226303495126:ios:26a9a1603b039b8e7af277',
    messagingSenderId: '226303495126',
    projectId: 'bonding-bdf7a',
    storageBucket: 'bonding-bdf7a.firebasestorage.app',
    iosBundleId: 'com.solla.bondingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOzmhcLX8GCPFmBExlWPXUR5qUrATYD4',
    appId: '1:226303495126:ios:26a9a1603b039b8e7af277',
    messagingSenderId: '226303495126',
    projectId: 'bonding-bdf7a',
    storageBucket: 'bonding-bdf7a.firebasestorage.app',
    iosBundleId: 'com.solla.bondingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQJzZ3kaAjRr_7LSbbDp88fapLph32AGE',
    appId: '1:226303495126:web:cd873a31d3ee68a57af277',
    messagingSenderId: '226303495126',
    projectId: 'bonding-bdf7a',
    authDomain: 'bonding-bdf7a.firebaseapp.com',
    storageBucket: 'bonding-bdf7a.firebasestorage.app',
    measurementId: 'G-E20RZ28MZ6',
  );
}
