-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpH03ZiLGHvTMbZS1
hLiXI3MZiXVhmLIhgdMiJfirgn2gCgYIKoZIzj0DAQehRANCAAT29IbhfnAe7qUY
ci1wKLHLkYloK/FS20fyNKynIGyBTXIEkC9WDXsClxrQHYSYI0CYAbasgqjkZ7Wc
DT65mfib
-----END PRIVATE KEY-----